services:
  backend:
    build: ./backend
    container_name: hospital-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: hospital-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
    restart: unless-stopped
